name: Rubocop

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run Rubocop
        uses: luizfonseca/github-actions-rubocop@2.0.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
